# Resumen del Paquete
package_name: regression_model

# Archivos de Datos
training_data_file: train.csv
test_data_file: test.csv

# Variables
# Variable que estamos intentando predecir (precio de venta)
target: SalePrice

pipeline_name: regression_model
pipeline_save_file: regression_model_output_v

# Provocará errores de sintaxis ya que comienzan con números
variables_to_rename:
  1stFlrSF: FirstFlrSF
  2ndFlrSF: SecondFlrSF
  3SsnPorch: ThreeSsnPortch

features:
  - MSSubClass
  - MSZoning
  - LotFrontage
  - LotShape
  - LandContour
  - LotConfig
  - Neighborhood
  - OverallQual
  - OverallCond
  - YearRemodAdd
  - RoofStyle
  - Exterior1st
  - ExterQual
  - Foundation
  - BsmtQual
  - BsmtExposure
  - BsmtFinType1
  - HeatingQC
  - CentralAir
  - FirstFlrSF # renombrado
  - SecondFlrSF # renombrado
  - GrLivArea
  - BsmtFullBath
  - HalfBath
  - KitchenQual
  - TotRmsAbvGrd
  - Functional
  - Fireplaces
  - FireplaceQu
  - GarageFinish
  - GarageCars
  - GarageArea
  - PavedDrive
  - WoodDeckSF
  - ScreenPorch
  - SaleCondition
  # solo para calcular la variable temporal:
  - YrSold

# Configuración de división de entrenamiento/prueba
test_size: 0.1

# Configuración de semilla aleatoria
random_state: 0

alpha: 0.001

# Variables categóricas con NA en el conjunto de entrenamiento
categorical_vars_with_na_frequent:
  - BsmtQual
  - BsmtExposure
  - BsmtFinType1
  - GarageFinish

categorical_vars_with_na_missing:
  - FireplaceQu

numerical_vars_with_na:
  - LotFrontage

temporal_vars:
  - YearRemodAdd

ref_var: YrSold

# Variables para transformación logarítmica
numericals_log_vars:
  - LotFrontage
  - FirstFlrSF
  - GrLivArea

binarize_vars:
  - ScreenPorch

# Variables para mapear
qual_vars:
  - ExterQual
  - BsmtQual
  - HeatingQC
  - KitchenQual
  - FireplaceQu

exposure_vars:
  - BsmtExposure

finish_vars:
  - BsmtFinType1

garage_vars:
  - GarageFinish

categorical_vars:
  - MSSubClass
  - MSZoning
  - LotShape
  - LandContour
  - LotConfig
  - Neighborhood
  - RoofStyle
  - Exterior1st
  - Foundation
  - CentralAir
  - Functional
  - PavedDrive
  - SaleCondition

# Mapeos de variables
qual_mappings:
  Po: 1
  Fa: 2
  TA: 3
  Gd: 4
  Ex: 5
  Missing: 0
  NA: 0

exposure_mappings:
  No: 1
  Mn: 2
  Av: 3
  Gd: 4

finish_mappings:
  Missing: 0
  NA: 0
  Unf: 1
  LwQ: 2
  Rec: 3
  BLQ: 4
  ALQ: 5
  GLQ: 6

garage_mappings:
  Missing: 0
  NA: 0
  Unf: 1
  RFn: 2
  Fin: 3
