# =======CONFIGURACIONES GENERALES Y PREPARACION DE ENTORNO=======

# Versión de la configuración de CircleCI
version: "2.1"

# Definición de esferas (orbs) para reutilización
orbs:
  node: circleci/node@5.1.0 # Se utiliza el orb 'circleci/node' en la versión 5.1.0

# Configuraciones predeterminadas para el trabajo
defaults: &defaults
  docker:
    - image: cimg/python:3.11.1 # Imagen de Docker con Python 3.11.1
  working_directory: ~/project # Directorio de trabajo predeterminado

# Crear un entorno virtual (venv) y actualizar pip
prepare_venv: &prepare_venv
  run:
    name: Create venv
    command: |
      python -m venv venv
      source venv/bin/activate
      pip install --upgrade pip

# Instalar tox para gestionar entornos de prueba
prepare_tox: &prepare_tox
  run:
    name: Install tox
    command: |
      pip install --user tox

# Activar el entorno virtual y ejecutar script para obtener datos
fetch_data: &fetch_data
  run:
    name: Set script permissions and fetch data
    command: |
      source venv/bin/activate
      chmod +x ./scripts/fetch_kaggle_dataset.sh
      ./scripts/fetch_kaggle_dataset.sh

# =======DEFINICION DE TRABAJADOS Y PASOS DE EJECUCION=======
jobs:
  # Trabajo para probar la aplicación
  test_app:
    <<: *defaults
    working_directory: ~/project/house-prices-api
    steps:
      - checkout:
          path: ~/project
      - *prepare_tox
      - run:
          name: Runnning app tests
          command: |
            tox

  # Trabajo para implementar la aplicación en Railway
  deploy_app_to_railway:
    <<: *defaults
    steps:
      - checkout:
          path: ~/project/
      - node/install:
          node-version: "16.13"
      - run: node --version
      - run: npm i -g @railway/cli
      - run:
          name: Deploy to Railway App (You must set RAILWAY_TOKEN env var)
          command: |
            cd house-prices-api && railway up --detach -s famed-board -e production

  # Trabajo para probar y cargar el modelo de regresión
  test_and_upload_regression_model:
    <<: *defaults
    working_directory: ~/project/model-package
    steps:
      - checkout:
          path: ~/project
      - *prepare_tox
      - run:
          name: Fetch the data
          command: |
            tox -e fetch_data
      - run:
          name: Test the model
          command: |
            tox
      - run:
          name: Publish model to Gemfury
          command: |
            tox -e publish_model

# Filtro que se aplica solo a las etiquetas (tags) en los cambios de git
tags_only: &tags_only
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /^.*/

# Definición del flujo de trabajo
workflows:
  version: 2
  deploy_pipeline:
    jobs:
      - test_app
      - deploy_app_to_railway:
          requires:
            - test_app
          filters:
            branches:
              only:
                - main
                - dev
      # Subir después de que se crean las etiquetas en git
      - test_and_upload_regression_model:
          <<: *tags_only
